version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startup.sh
